# Generated by Django 4.0.3 on 2022-04-03 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_task_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='first_task_app.asset'),
        ),
        migrations.DeleteModel(
            name='UserAsset',
        ),
    ]
