# Generated by Django 4.0.3 on 2022-04-03 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_task_app', '0002_profile_asset_delete_userasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='first_task_app.language'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_invest_pc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='money',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='portfolio_calc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stop_loss_pc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='typ',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_currency',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='userexchange',
            name='api_key',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userexchange',
            name='api_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='userexchange',
            name='secret_key',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
