# Generated by Django 4.0.3 on 2022-04-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_task_app', '0002_remove_asset_user_userasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_currency',
            field=models.CharField(blank=True, choices=[('EUR', 'EUR'), ('USD', 'USD'), ('CHF', 'CHF'), ('GBP', 'GBP'), ('BTC', 'BTC'), ('ETH', 'ETH')], max_length=30),
        ),
    ]
