# Generated by Django 4.0.3 on 2022-04-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_task_app', '0003_alter_profile_language_alter_profile_max_invest_pc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexchange',
            name='portfolio_calc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userexchange',
            name='portfolio_rest',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
