# Generated by Django 4.0.3 on 2022-04-16 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_task_app', '0004_profile_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_verified',
        ),
    ]
